### ISSUE TITLE
Determine which droopy section / subsection was tapped

### ISSUE THREAD

**Issue by daviddelmonte** [cemolcay/DroppyExpandingSectionView#1]
How do you suggest I trap which section/subsection was tapped, so that I can perform specific actions?

Thanks.. Love the control.

**Comment by cemolcay** [comment]
hi, thanks.
since sections and their items are UIView's, you can assign them tap gesture recognizers or you can use UIButtons instead of UIView, because buttons are UIView subclasses.
Or you can use something [like that](https://gist.github.com/cemolcay/c4fe49ea2c34ce8ddab6) :+1:

**Comment by daviddelmonte** [comment]
Thanks! I've tried using both methods. I cannot get buttons to fire, and the same of gestures. I'll try again though

**Comment by cemolcay** [comment]
i updated the repo. Section items were child of section header view, that was the problem because items weren't inside section header frame, and doesn't respond the touches. 
In the new demo i added tap gestures to section items, check it out :+1:

**Comment by daviddelmonte** [comment]
Brilliant. Just what I needed. Thanks a lot!! I really appreciate it.
